module.exports = {
	artifact: ['name', 'rarity', 'exclusive', 'loreDescription', 'skillDescription', 'stats'],
	'buff-debuff': ['title', 'description'],
	hero: [
		'gameId',
		'name',
		'rarity',
		'classType',
		'element',
		'zodiac',
		'specialtyChangeName',
		'selfSkillBarName',
		'background',
		'relations',
		'stats',
		'skills',
		'specialtySkill',
		'memoryImprintFormation',
		'camping',
		'memoryImprint',
		'awakening',
		'summonQuote',
		'description',
	],
	item: ['name', 'locations', 'description', 'type', 'rarity'],
	latest: ['hero', 'artifact'],
	voice: ['_id', 'voice'],
	creator: ['title', 'description', 'img', 'social'],
	ex_equip: ['name', 'description', 'heroId', 'stat', 'enhancements'],
};
