module.exports = {
	artifact: ['name', 'rarity', 'exclusive', 'loreDescription', 'skillDescription', 'stats'],
	'buff-debuff': ['title', 'description'],
	hero: [
		'name',
		'rarity',
		'classType',
		'element',
		'zodiac',
		'specialtyChangeName',
		'selfSkillBarName',
		'background',
		'relations',
		'stats',
		'skills',
		'specialtySkill',
		'memoryImprintFormation',
		'camping',
		'memoryImprint',
		'awakening',
	],
	item: ['name', 'locations', 'description', 'type', 'rarity'],
};
